algorithms/data_structure/GainLee/Boj_10799.java, algorithms/data_structure/GainLee/Boj_1966.java, algorithms/data_structure/GainLee/Boj_22942.java
=> [ADD] GainLee 1주차

algorithms/data_structure/moomin/G1918.java, algorithms/data_structure/moomin/G22942.java, algorithms/data_structure/moomin/G2504.java, algorithms/data_structure/moomin/S10799.java, algorithms/data_structure/moomin/S1874.java, algorithms/data_structure/moomin/S1966.java, algorithms/data_structure/moomin/S2346.java
=> [ADD] moomin 1주차

algorithms/data_structure2/k0000k/Bj11279.java, algorithms/data_structure2/k0000k/Bj11286.java, algorithms/data_structure2/k0000k/Bj21939.java, algorithms/data_structure2/k0000k/Bj21944.java, algorithms/data_structure2/k0000k/Bj4358.java
1. 4358 생태학 (실버 2)
Java로는 EOF를 처리해본적이 없어서, 이 부분을 공부했던 문제입니다. 어렵지는 않았지만 EOF, String Formatting, 소수 자료형 등 신경 쓸 부분이 좀 있는 문제였습니다.
2. 11279 최대 힙 (실버2)
이전에 파이썬으로 푼 적이 있는 문제라서 자바로 다시 풀었습니다. 단순히 정수를 큰 수 순서로 정렬하면 되므로, 따로 Comparator나 Comparable 사용하지 않고, 음수로 바꾸어서 pq에 넣고 뺐습니다.
3. 11286 절댓값 힙 (실버1)
이 문제 역시 파이썬으로 풀이한 적이 있습니다. 바로 전 문제와 다르게 절댓값을 기준으로 정렬해야 하므로, pq를 선언할 때 Comparator를 만들었습니다.
4. 21939 문제 추천 시스템 Version 1 (골드4)
특별한건 없습니다! 그냥 문제 요구사항에 맞게 구현하였고, 최소와 최대 우선순위 큐 두개 굴리면서 했습니다. add와 solved 연산 할 때마다 두개의 큐에 똑같이 연산하면 되고, recommend 연산은 조회 연산만 수행하므로 두개의 큐를 편하게 사용해도 괜찮다고 판단했습니다.
5. 21944 문제 추천 시스템 Version 2 (골드2)
ver1 문제를 생각없이.. 구현했다가 피 봤습니다. 윗 문제 코드를 기반으로 구현했다가 시간 초과의 늪에서 이틀을 헤맸습니다. 그러다 TreeSet을 도입해서 새로 구현하게 됐고, 이 과정에서 TreeSet의 remove는 equals()가 아닌 compareTo() 기반으로 동작한다는 사실을 배우게 되었습니다. 그럼에도 불구하고 여전히 …
=> [ADD] K0000k 2주차

algorithms/data_structure2/moomin/G21944.java, algorithms/data_structure2/moomin/G24939.java, algorithms/data_structure2/moomin/S11279.java, algorithms/data_structure2/moomin/S11286.java, algorithms/data_structure2/moomin/S4358.java
- 4358 생태학 (실버 2)
사실 문제가 어려웠다기 보다는 항상 정해진 만큼의 입력만 받다가
입력이 끝났음을 어떻게 알릴까 고민하다가 시간이 지체된 문제
찾아보니 백준에서는 그냥 null 처리만 해줘도 답으로 인정해준다고 함.
다만 인텔리제이 환경에서는 공백이 null 입력으로 받아드려지지 않아서
종료 키워드 하나 정해놓고 테스트함 !
- 11279 최대 힙 (실버2)
우선순위 큐를 사용하여 쉽게 해결함!
- 11286 절댓값 힙 (실버1)
예전에 한번 풀었던 적이 있는 문제!
다시 풀어봐도 절댓값 중심으로 정렬을 재정의하는 건 헷갈린다..!
- 21939 문제 추천 시스템 Version 1 (골드4)
자바 문법을 잘 몰라서 시간이 지체되었던 문제..
recommend -1 명령에서 단순히 우선순위 큐를 toList나 toArray로 변경하였는데
그럴 시에 순서가 보장되지 않다는 것을 알게됨!!!!!
그래서 ArrayList로 해결함 :) (이때는 Priority Queue만 알았던 시절..)
- 21944 문제 추천 시스템 Version 2 (골드2)
길고 길었던...3일만에 겨우 풀어낸 질긴 문제.... 나름 Version1을 이쁘게 풀었다고 생각했는데 자바에서 Map, Set에 대한 개념을 잘 모르다보니 활용력이 떨어져서 고생했던 ㅠㅠ 그래도 이번 기회를 통해 참 많은 함수들을 찾아보고 사용해볼 수 있었던 문제!!
=> [ADD] moomin 2주차

algorithms/data_structure2/GainLee/Boj_11279.java, algorithms/data_structure2/GainLee/Boj_11286_2nd_try.java, algorithms/data_structure2/GainLee/Boj_21939.java, algorithms/data_structure2/GainLee/Boj_21944.java, algorithms/data_structure2/GainLee/Boj_4358.java
✔️	[4358](https://www.acmicpc.net/problem/4358)	[생태학](https://www.acmicpc.net/problem/4358)		
✔️	[11279](https://www.acmicpc.net/problem/11279)	[최대 힙](https://www.acmicpc.net/problem/11279)		
✔️	[11286](https://www.acmicpc.net/problem/11286)	[절댓값 힙](https://www.acmicpc.net/problem/11286)
✔️	[21939](https://www.acmicpc.net/problem/21939)	[문제 추천 시스템 Version 1](https://www.acmicpc.net/problem/21939)		
[21944](https://www.acmicpc.net/problem/21944)	[문제 추천 시스템 Version 2](https://www.acmicpc.net/problem/21944)
=> [ADD] 2주차 이가인

algorithms/tree/choyunju/BJ_11725.java, algorithms/tree/choyunju/BJ_1991.java, algorithms/tree/choyunju/BJ_2250.java, algorithms/tree/choyunju/BJ_5639.java, algorithms/tree/choyunju/BJ_9934.java
**2250번**
계속 틀렸다고 나와서 뭐가 문제인지 엄청 찾아봤는데 알고보니 root를 무조건 1번으로 설정했더라고요,,,,
root 노드는 1이 아닌 부모 노드가 존재하지 않는 노드입니다!
앞으로 문제를 잘 읽어봐야겠습니다ㅠㅠ!
=> [ADD] choyunju 3주차

algorithms/tree/moomin/G5639.java, algorithms/tree/moomin/S11725.java, algorithms/tree/moomin/S1991.java, algorithms/tree/moomin/S9934.java
**👉 S11725 트리의 부모 찾기 (실버2)**
BFS로 쌈뽕하게 해결! (다만, 중간에 왜 bfs를 for문안에 넣었는지 본인도 의문인.... 호다닥 수정함)
**👉 S1991 트리 순회 (실버 1)**
강의에서 배운 트리 순회하는 방법을 그대로 따라한 문제
**👉 S9934 완전 이진 트리 (실버1)**
완전한 이진 트리라는 점과 중위 순회에 초점을 두면 크게 어렵지는 않았던 문제
**👉 G5639 이진 검색 트리 (골드4)**
어떤 방법으로 풀 것인가를 고민하는데 시간을 많이 들인 문제
트리를 빡구현 할 것인지 주어진 순회결과를 재귀적으로 탐색할 것인지를 고민하다가 결국 귀찮아서 트리를 구현하여 해결함. 다만, 두 가지의 해결방안이 떠올랐을 때 모두 구현해보는 것도 실력을 높이는데 기여할 것 같아서 앞으로는 귀찮더라도 모두 시도해보기로..!!
**👉 G2250 트리의 높이와 너비 (골드2)**
아놔 진짜 그림보고 RUN칠뻔한 문제였으나,, 제목대로 트리의 높이와 너비에 집중하니 길이 보이는 듯한 문제.. 근데 아직 구현 안함,,ㅎㅎㅎ
=> [ADD] moomin 3주차

algorithms/greedy/choyunju/BJ_1541.java, algorithms/greedy/choyunju/BJ_16953.java, algorithms/greedy/choyunju/BJ_21314.java, algorithms/greedy/choyunju/BJ_2141.java, algorithms/greedy/choyunju/BJ_8980.java
**no.8980**
분명 회의실 문제랑 비슷해서 정렬하는 것까진 알았는데 그 뒤에 어떻게 최대 박스의 수를 구해야 할까 고민하다가 같이 공부하던 친구가 이 문제를 풀었어서 각 마을마다 담을 수 있는 용량을 저장하라고 힌트 아닌 정답을 알려줘서 겨우 풀었습니다...ㅋㅋㅋ
**no.2141**
@k0000k 님의 도움으로 풀었습니다,,,ㅠ 그래프를 어떻게 해석해야 하나 고민 도중 음수에서 양수가 되는 기울기를 찾으면 된다는 도움을 받았습니다..! 이 문제를 통해 수학적(?)인 문제도 연습을 해야 할 것같아요,,
=> [ADD] choyunju 4주차

algorithms/greedy/moomin/G2141.java, algorithms/greedy/moomin/S1541.java, algorithms/greedy/moomin/S16953.java, algorithms/greedy/moomin/S21314.java
**- 16953 A -> B (실버2)**
사실 어떻게 풀지보다 그냥 문자열 어찌 처리할지에 집중했던 문제!
**- 1541 잃어버린 괄호 (실버2)**
괄호를 왜 잃어버리고 난리야.... 흐흐 - 기준으로 토큰화 한 뒤 +를 품고있는 아이들을 다 더해주고 첫번째 원소에서 싸그리 뺐습니다!
**- 21314 민겸 수 (실버1)**
민경 수로 바꿔주세요 ^_^
문자열로 시도하는거까지는 어렵지 않았는데 어떤 상황에서 최대인지를 고려 안하고 냅다 숫자로 바꿨다가 시간 좀 걸렸다는..
그리디 문제에서는 최대/최소가 어떤 형태여야 하는지 꼼꼼히 보기
**- 2141 우체국 (골드4)**
아이디어 싸움에 졌다.... 마을 위치에 계속 포커스를 맞췄는데 인구를 고려하게 되면 바로 풀려버리는,, 
이런 생각 어케 바로바로 떠올리냐
**- 8980 택배 (골드1)**
아직,,, 택배를 보내지 못함 ㅠ.ㅜ
=> [ADD] moomin 4주차

algorithms/dynamic_programming_1/k0000k/Bj11055.java, algorithms/dynamic_programming_1/k0000k/Bj2293.java, algorithms/dynamic_programming_1/k0000k/Bj2294.java, algorithms/dynamic_programming_1/k0000k/Bj2579.java, algorithms/dynamic_programming_1/k0000k/Bj9465.java
**2579 계단 오르기 (실버 3)**
점화식이 안나와서 정말 너무너무 어려웠습니다... 결국 알고리즘 장인분께 배워와서 풀었네요... 1칸을 오르는 경우에는 그 이전에 반드시 2칸을 오르게 하면 된다는걸 놓치고 있었어서 못풀었습니다. 참 DP는 난이도가 의미 없는 것 같네요.. 오히려 이거보다 높은 티어에 쉬운 문제가 많은 것 같아요ㅠㅠ **_이번주 문제 다 풀고나서 봐도 이게 제일 어렵습니다._**
**11055 가장 큰 증가하는 부분 수열 (실버 2)**
크게 어렵지 않았으나, 처음에 반례를 다 못찾아서 틀렸었습니다!
**9465 스티커 (실버 1)**
이전에 파이썬으로 풀이한 문제입니다. 이번엔 자바로 다시 풀어봤습니다.
**2294 동전 2 (골드 5)**
같은 가치의 동전이 있어도 영향을 주지 않도록 하는데 신경을 썼습니다. 그 외에는 그냥 유명한 동전문제입니다!
**2993 동전 1 (골드 4)**
진짜 어이없게 한번 틀린문제... 문제를 잘 읽어야해요.. 문제 어디에도 k보다 작은 동전만 들어온다고 한적이 없습니다.. IndexOutOfBound 떠서 당황한문제..!
=> [ADD] k0000k 5주차

algorithms/dynamic_programming_1/choyunju/BJ_11055.java, algorithms/dynamic_programming_1/choyunju/BJ_2293.java, algorithms/dynamic_programming_1/choyunju/BJ_2294.java, algorithms/dynamic_programming_1/choyunju/BJ_2579.java, algorithms/dynamic_programming_1/choyunju/BJ_9465.java
**no. 2579 - 계단 오르기**
처음으로 DP 문제를,,,,풀어본 것 같은데 너무 막막해서 결국 알고리즘 마스터께 도움을 요청하여 풀었습니다,,,점화식을 생각해 내는 게 제일 어려운 것 같습니다 ㅠㅠ 특히 인덱스가 첫 번째와 두 번째인 경우를 따로 설정해야 했는데 이 부분을 생각하지 못해 많이 실패했습니다,,
**no. 11055 - 가장 큰 증가하는 부분 수열**
대충 DP에 어떻게 저장해야 할지 느낌은 알았지만 코드로 구현하기까지 아직 어려워서 이 문제도 2579문제를 푸는데 도움을 주셨던 알고리즘 마스터께 도움을 받았습니다...! 
**no. 9465 - 스티커**
위의 두 문제보다 난이도는 더 높은데 개인적으로 두 문제보다 잘 풀렸던 문제였습니다...! 위의 두 문제를 푸셨다면 그 접근과 비슷하게 풀면 될 것같습니다. 저는 이차원배열로 풀었습니다!
=> [ADD] choyunju 5주차

algorithms/dynamic_programming_1/moomin/G2293.java, algorithms/dynamic_programming_1/moomin/G2294.java, algorithms/dynamic_programming_1/moomin/S11055.java, algorithms/dynamic_programming_1/moomin/S2579.java, algorithms/dynamic_programming_1/moomin/S9465.java
- 모든 문제를 풀어가는 과정이 비슷하였던 것 같습니다😊
- 저는 문제를 작게 생각하는 건 어렵지 않은데 너무 작게 생각한 나머지 규칙을 추상화 하는 과정에서 어려움이 좀 있었숩니당
- DP는 감을 잃지 않도록 꾸준히 풀어야겠습니다 !
=> [ADD] moomin 5주차

algorithms/dynamic_programming_2/k0000k/Bj12865.java, algorithms/dynamic_programming_2/k0000k/Bj15724.java, algorithms/dynamic_programming_2/k0000k/Bj17485.java, algorithms/dynamic_programming_2/k0000k/Bj2631.java
**15724 주지수**
완전 똑같은!! 문제가 Class 4에 있습니다. '11660 구간 합 구하기 5' 문제인데요, 참고해보셔도 좋을 것 같습니다.
**12865 평범한 배낭**
배낭 문제.. 얼마전에 공부하다 던져버렸는데, 이번 기회에 마무리 했습니다!
**17485 진우의 달 여행**
너무 어려웠습니다ㅜㅜ 가인님이 도움 주셔서 풀었고,,, 3차원 DP 배열로 만들어서 방향까지 저장해야 한다는 생각을 못했네요...!
**2631 줄 세우기**
알아채는데까지 시간이 걸렸습니다,, 아니 알고보니 그냥 가장 긴 증가하는 부분수열 찾기자나! 코드는 별게없네요
=> [ADD] K0000k 6주차

algorithms/dynamic_programming_2/moomin/G12865.java, algorithms/dynamic_programming_2/moomin/G1695.java, algorithms/dynamic_programming_2/moomin/G2631.java, algorithms/dynamic_programming_2/moomin/S15724.java
- 15724 주지수 (실버1)
DP보다는,, 누적합으로 풀었습니당
- 12865 평범한 배낭 (골드5)
저는 일차원 배열로 해결했는데 2차원 배열로 풀면 더 보기에 깔끔할 것 같아요 -!
- 2631 줄세우기 (골드4)
가장 긴 증가하는 수열의 스토리 버전!
- 1695 팰린드롬 만들기 (골드5)
LCS의 스토리 버전!
- 17485 진우의 달여행 (골드5)
달나라 못감 이슈..
=> [ADD] moomin 6주차

algorithms/dynamic_programming_2/choyunju/BJ_12865.java, algorithms/dynamic_programming_2/choyunju/BJ_15724.java, algorithms/dynamic_programming_2/choyunju/BJ_1695.java, algorithms/dynamic_programming_2/choyunju/BJ_17485.java, algorithms/dynamic_programming_2/choyunju/BJ_2631.java
**12865**
하루종일 고민하다가 도저히 점화식을 어떻게 구현해야 할 지 감도 못찾아서 대충 검색해보니 배낭 문제(knapsack)로 유명한 문제였습니다. 그래서 해당 알고리즘에 대해 처음부터 공부해보고 다시 이 문제를 풀어보니 DP를 1차원으로만 풀으려고 하니 계속 못 풀었구나를 깨달았습니다,,DP 문제는 확실히 많이 풀어봐야지 감을 잡을 수 있는 것 같아요,,!
=> [ADD] choyunju 6주차

algorithms/two_pointer/k0000k/Bj20366.java, algorithms/two_pointer/k0000k/Bj20442.java, algorithms/two_pointer/k0000k/Bj20922.java, algorithms/two_pointer/k0000k/Bj21921.java, algorithms/two_pointer/k0000k/Bj22862.java
**21921 블로그 (실버 3)**
간단한 투포인터 문제입니다.
**20922 겹치는 건 싫어 (실버 1)**
큐에 수열의 원소를 하나씩 담고, 조건에 어긋난다면 반대쪽에서 하나씩 빼면서 최댓값을 찾았습니다. 많이 쓰이는 방법으로 풀 수 있었습니다.
**22862 가장 긴 짝수 연속한 부분 수열 (large) (골드 5)**
그냥,, 홀짝만 표시해주면 바로 윗 문제랑 완전 똑같이 풀이 가능합니다. 개인적으로는, 윗 문제는 모든 숫자의 갯수를 관리해야 하는 반면, 이 문제에서는 홀짝 두 가지만 관리하면 되니까 이게 더 쉬운 문제여야만 할 것 같습니다...
**20366 같이 눈사람 만들래? (골드 3)**
이틀동안 봤는데 저의 능력이 부족한 것 같습니다! 결국 못풀고 아래 링크를 보고 공부했으니 참고해주세요. 
(1) 눈덩이를 정렬한다.
(2) 모든 (i, j) 쌍에 대해 아래를 수행한다. i와 j 사이에는 2개 이상의 눈덩이가 있어야 한다.
(3) i와 j 사이의 눈덩이로 최적의 두번째 눈사람을 탐색한다. start = i + 1, end = j - 1로 두고 투포인터 탐색을 시작한다.
(4) 투포인터 눈사람이 (i, j) 눈사람보다 키가 크면 end--, 키가 작으면 start++ 한다. (투포인터가 가리키는 눈사람이 (i, j) 구간 내에서 최적의 후보가 되는 눈사람이다.)
(5) 새로운 눈사람을 찾을때마다 키 차이를 비교한다.
https://yinq.tistory.com/254
**20442 ㅋㅋ루ㅋㅋ (골드 2)**
월요일 오후까지 반례를 못찾아서 결국 벌금 냈지만,,,^^ 풀었습니다! 우선 문제 …
=> [ADD] k0000k 7주차

algorithms/two_pointer/moomin/G20366.java, algorithms/two_pointer/moomin/G22862.java, algorithms/two_pointer/moomin/S20922.java, algorithms/two_pointer/moomin/S21921.java
- ㅋㅋ루ㅋㅋ 제외하고 풀었습니다...
- 투포인터는 언제 늘어나고 언제 줄어드는지 파악하면서 푸는 것이 가장 중요한 것 같아요 !
=> [ADD] moomin 7주차

algorithms/implementation/k0000k/Bj14719.java, algorithms/implementation/k0000k/Bj16926.java, algorithms/implementation/k0000k/Bj17276.java, algorithms/implementation/k0000k/Bj22856.java, algorithms/implementation/k0000k/Bj2615.java
**2615 오목 (실버 1)**
첫 문제부터 순탄치 않군요. 틀려서 깜지엔딩... 왼쪽 아래쪽으로 5개가 줄지어 있는 경우를 생각하지 못했습니다. 그리고 제일 왼쪽 돌을 출력해야하는데 윗쪽꺼를 프린트하고 있었네요,,, 😢 
**17276 배열 돌리기 (실버 1)**
어렵지는 않았지만 아주 귀찮았던 문제네요. 버퍼 역할을 하는 배열 하나를 놓고 풀었습니다.
**14719 빗물 (골드 5)**
배열 전체를 순회하면서 높이가 h인 블럭을 계속 찾습니다. 그리고 찾은 블럭 사이에 물이 차오릅니다. h를 0까지 줄이면서 이 과정을 반복하면 됩니다.
**16926 배열 돌리기 1 (골드 5)**
아 이게 왜 골드5야!!! 제일 어렵네요ㅜ 교훈은... 이쁘고 깔끔하게 풀려고 노력하지 말자... 그냥 구현하자..
**22856 트리 순회 (골드 4)**
중위순회인데 방문처리를 맨 처음에 해버려서 바보같이 한 번 틀린 문제... (깜지엔딩)
=> [ADD] k0000k 8주차

algorithms/implementation/moomin/G14719.java, algorithms/implementation/moomin/G16926.java, algorithms/implementation/moomin/G22856.java, algorithms/implementation/moomin/S17276.java, algorithms/implementation/moomin/S2615.java
=> [ADD] moomin 8주차

algorithms/brute_force/moomin/G15661.java
> 두 팀의 차이가 최소로 나게끔 팀빌딩한다!
- 무조건 전체인원의 절반씩 팀을 분리하는게 차이가 가장 작을꺼라는 생각에 요대로 구현했다가 86%에서 오류
- 그리고 나서 팀을 나누는 모든 경우의 수를 다 탐색함
=> [ADD] moomin 10주차

algorithms/brute_force/choyuju/BJ_14500.java, algorithms/brute_force/choyuju/BJ_15661.java, algorithms/brute_force/choyuju/BJ_16637.java, algorithms/brute_force/choyuju/BJ_21278.java, algorithms/brute_force/choyuju/BJ_21315.java
> 간단한 문제 요약
- 핵심 아이디어 요약
- 시간복잡도, 어려웠던 점, 공부한 점 등 자유롭게
=> [ADD] choyunju 10주차

algorithms/simulation/k0000k/Bj14891.java, algorithms/simulation/k0000k/Bj15683.java, algorithms/simulation/k0000k/Bj20055.java, algorithms/simulation/k0000k/Bj20165.java, algorithms/simulation/k0000k/Bj21922.java
> 사이클 처리에 유의하면서 바람이 들어오는 자리를 모두 찾습니다.
- 사이클이 생길 것 같은데? 루프를 어떻게 끊지?를 신경 쓴 문제입니다. 관찰해보니 사이클이 생기더라도 에어컨을 한번 만나면 종료해도 되겠더라구요!
- 그 외에는 문제에 나온대로 구현했습니다.
---
> 도미노를 연쇄적으로 쓰러트려야 합니다.
- 연쇄적으로 쓰러지는 것을 재귀로 구현해야 합니다. 이 부분 신경쓰면 특이사항은 없네요.
---
> 톱니바퀴를 회전 시킬 때 영향 받는 톱니바퀴를 모두 찾아서 회전시키고, 마지막에 점수를 계산합니다.
- 이전에 한 번 풀어본 적이 있는 문제입니다.
- 지난번보다 깔끔하게 풀고 주석도 달아봤습니다.
---
> 2n 길이의 컨베이어 벨트가 있고, 로봇을 올릴 수 있는 범위는 n입니다. 매번 컨베이어 벨트가 돌아가는데, 언제까지 돌릴 수 있는지를 찾는 문제입니다.
- 괜히 회전 큐 만들어서 돌리려고 머리쓰다가 시간을 많이 쓴 문제입니다! 어차피 n이 최대 100인데.. 그냥 배열 만들어서 풀어도 충분하네요.
---
> 가능한 모든 경우를 빠짐없이 탐색하여 최솟값을 찾습니다..
- 그냥 보자마자 브루트포스 직감했습니다... 어떻게 효율적으로 코드 짤지가 관건이였네요..ㅠㅠ 빡빡빡빡구현
---
=> [ADD] k0000k 11주차

algorithms/simulation/GainLee/Boj_14891.java, algorithms/simulation/GainLee/Boj_20055.java
> 4개의 톱니바퀴의 상태가 주어지고, 회전시킨 톱니바키의 번호와 방향이 주어질때, 회전 이후의 톱니바퀴들의 점수의 합을 구하는 문제입니다.
- 자료형에 대한 고민이 많았던 문제입니다.. 처음엔 2차원 배열로 생각했다가, 원형큐로도 생각을 했었습니다. Collections.rotate()를 쓰면 정말 쉽게 배열을 회전시킬 수 있다는 것을 알고 ArrayList를 사용했습니다~
- num 번째의 톱니바퀴를 돌리면 왼쪽과 오른쪽의 톱니바퀴에 영향이 가므로, 재귀함수를 사용해야 합니다.
- visited 배열을 이용해 무한루프에 빠지지 않도록 해야합니다.
- 이때 visited 배열의 초기화는 회전을 시작할때마다 해주어야 합니다! (이부분에 대한 감을 잘 못잡았네요~)
- 점수의 합은 각 톱니바퀴의 첫번째 원소가 1일때만 더해주면 됩니다. 2^num (num은 톱니바퀴의 인덱스)임을 이용하면 쉽게 더할 수 있습니다.
---
> 컨베이어 벨트를 회전하고, 물건을 내리는 문제입니다.
- 톱니바퀴의 후유증으로 Collections.rotate()를 사용할까 고민했습니다. rotateRobot(), rotateBelt() 메서드를 만들어 문제를 해결하고 있다가 마감 이슈로 혜경이 코드 보고 깜지쓰는 것으로 마무리 하게 되었습니다......
---
=> [ADD] GainLee 11주차

algorithms/simulation/choyunju/BJ_14891.java, algorithms/simulation/choyunju/BJ_15683.java, algorithms/simulation/choyunju/BJ_20055.java, algorithms/simulation/choyunju/BJ_20165.java, algorithms/simulation/choyunju/BJ_21922.java
> 간단한 문제 요약
- 핵심 아이디어 요약
- 시간복잡도, 어려웠던 점, 공부한 점 등 자유롭게
=> [ADD] choyunju 11주차
